import sys
import re
from sqlalchemy.orm import Session
from db import SessionLocal, engine, Base
from models import FamilyMember

Base.metadata.create_all(bind=engine)

def parse_gedcom(filepath):
    """
    Parses a simple standard GEDCOM file generated by the Family Tree app.
    Returns: individuals (dict), families (dict)
    """
    individuals = {}
    families = {}
    current_record_type = None
    current_id = None
    
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    for line in lines:
        line = line.strip()
        if not line: continue
        
        parts = line.split(' ', 2)
        level = parts[0]
        
        if level == '0':
            if len(parts) == 3:
                tag = parts[2]
                record_id = parts[1].strip('@')
                if tag in ['INDI', 'FAM']:
                    current_record_type = tag
                    current_id = record_id
                    if tag == 'INDI':
                        individuals[current_id] = {
                            'full_name': 'Unknown', 'gender': 'male', 
                            'birth_year': None, 'death_year': None, 
                            'is_alive': True, 'profession': None, 'branch_name': None
                        }
                    elif tag == 'FAM':
                        families[current_id] = {'husband': None, 'wife': None, 'children': []}
        
        elif level == '1' and current_id:
            tag = parts[1]
            val = parts[2] if len(parts) > 2 else ""
            
            if current_record_type == 'INDI':
                if tag == 'NAME':
                    names = val.replace('/', '').strip()
                    individuals[current_id]['full_name'] = names
                elif tag == 'SEX':
                    individuals[current_id]['gender'] = 'male' if val == 'M' else 'female'
                elif tag == 'BIRT':
                    pass # Will read DATE on level 2
                elif tag == 'DEAT':
                    individuals[current_id]['is_alive'] = False
                elif tag == 'OCCU':
                    individuals[current_id]['profession'] = val
                elif tag == 'NOTE':
                    if val.startswith('Branch:'):
                        individuals[current_id]['branch_name'] = val.replace('Branch:', '').strip()
            
            elif current_record_type == 'FAM':
                if tag == 'HUSB':
                    families[current_id]['husband'] = val.strip('@')
                elif tag == 'WIFE':
                    families[current_id]['wife'] = val.strip('@')
                elif tag == 'CHIL':
                    families[current_id]['children'].append(val.strip('@'))
                    
        elif level == '2' and current_record_type == 'INDI' and current_id:
            tag = parts[1]
            val = parts[2] if len(parts) > 2 else ""
            # Simple assumption: previous tag was BIRT or DEAT
            # Standard GEDCOM actually needs a state variable, but this matches our export format
            prev_line = lines[lines.index(line + "\n") - 1] if line + "\n" in lines else ""
            if tag == 'DATE':
                if '1 BIRT' in prev_line or any('1 BIRT' in l for l in lines[max(0, lines.index(line+"\n")-2):lines.index(line+"\n")]):
                    individuals[current_id]['birth_year'] = int(val) if val.isdigit() else None
                elif '1 DEAT' in prev_line or any('1 DEAT' in l for l in lines[max(0, lines.index(line+"\n")-2):lines.index(line+"\n")]):
                    individuals[current_id]['death_year'] = int(val) if val.isdigit() else None

    return individuals, families

def import_data(filepath):
    print(f"Reading GEDCOM file: {filepath}")
    inds, fams = parse_gedcom(filepath)
    print(f"Found {len(inds)} individuals and {len(fams)} families.")
    
    db = SessionLocal()
    try:
        # 1. Insert all individuals and map old GEDCOM ID to new DB ID
        id_map = {}
        for old_id, data in inds.items():
            member = FamilyMember(**data)
            db.add(member)
            db.flush() # Get new ID
            id_map[old_id] = member.id
            
        # 2. Reconstruct family links (Parent -> Child)
        links = 0
        for fam_id, fam_data in fams.items():
            # In our system logic, a family has a single primary parent attached via parent_id
            # Usually the father if available, or the wife.
            parent_gedcom_id = fam_data['husband'] or fam_data['wife']
            if not parent_gedcom_id: continue
            
            parent_db_id = id_map.get(parent_gedcom_id)
            if not parent_db_id: continue
            
            for child_gedcom_id in fam_data['children']:
                child_db_id = id_map.get(child_gedcom_id)
                if child_db_id:
                    child = db.query(FamilyMember).filter(FamilyMember.id == child_db_id).first()
                    if child:
                        child.parent_id = parent_db_id
                        links += 1
                        
        db.commit()
        print(f"✅ Successfully imported {len(inds)} people and linked {links} child relationships.")
        
    except Exception as e:
        db.rollback()
        print(f"❌ Error during import: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 import_gedcom.py <gedcom_file.ged>")
        sys.exit(1)
    import_data(sys.argv[1])
